/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Coupang' at '14. 2. 20 오후 5:57' with Gradle 1.11
 *
 * @author Coupang, @date 14. 2. 20 오후 5:57
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
