/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'coollee' at '15. 11. 27 오후 11:16' with Gradle 2.9
 *
 * @author coollee, @date 15. 11. 27 오후 11:16
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
